# Generated by Django 3.0.4 on 2020-05-05 14:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import usuarios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is admin')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='is superuser')),
                ('nombre', models.CharField(max_length=20, verbose_name='nombre')),
                ('apellido1', models.CharField(max_length=30, verbose_name='apellido1')),
                ('apellido2', models.CharField(max_length=30, verbose_name='apellido2')),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha nacimiento')),
                ('telefono', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="El telefono debe introducirse con el formato: '+999999999' ", regex='^\\+?1?\\d{9,15}$')], verbose_name='telefono')),
                ('descripcion', models.TextField(default='', verbose_name='descripcion')),
                ('n_seguidores', models.IntegerField(default=0, verbose_name='seguidores')),
                ('n_seguidos', models.IntegerField(default=0, verbose_name='seguidos')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=usuarios.models.ruta_guardar)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioSeguido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seguido', models.DateTimeField(auto_now=True, verbose_name='fecha seguido')),
                ('usuario_seguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to=settings.AUTH_USER_MODEL)),
                ('usuario_seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario_seguidor', 'usuario_seguido')},
            },
        ),
    ]
