# Generated by Django 3.0.4 on 2020-05-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='n_publicaciones',
            field=models.IntegerField(default=0, verbose_name='publicaciones'),
        ),
    ]
