# Generated by Django 3.0.4 on 2020-03-30 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20200330_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='n_seguidores',
            new_name='seguidores',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='n_seguidos',
            new_name='seguidos',
        ),
        migrations.DeleteModel(
            name='Seguidor',
        ),
    ]
