# Generated by Django 3.0.4 on 2020-03-30 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20200330_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioSeguido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_publicado', models.DateTimeField(auto_now=True, verbose_name='fecha publicado')),
                ('usuario_seguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguido', to=settings.AUTH_USER_MODEL)),
                ('usuario_seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario_seguidor', 'usuario_seguido')},
            },
        ),
    ]
