# Generated by Django 3.0.4 on 2020-03-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuarioseguido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='seguidores',
            new_name='n_seguidores',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='seguidos',
            new_name='n_seguidos',
        ),
    ]
