# Generated by Django 3.0.4 on 2020-03-30 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20200330_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=usuarios.models.ruta_guardar),
        ),
        migrations.AlterField(
            model_name='usuarioseguido',
            name='usuario_seguido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuarioseguido',
            name='usuario_seguidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
