# Generated by Django 3.0.4 on 2020-03-28 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import publicaciones.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(default='', verbose_name='descripción')),
                ('localizacion', models.CharField(default='', max_length=100, verbose_name='localización')),
                ('fecha_publicado', models.DateTimeField(auto_now=True, verbose_name='fecha publicado')),
                ('fecha_editado', models.DateTimeField(auto_now_add=True, verbose_name='fecha editado')),
                ('n_likes', models.BigIntegerField(default=0, verbose_name='Nº likes')),
                ('n_comentarios', models.BigIntegerField(default=0, verbose_name='Nº comentarios')),
                ('es_imagen', models.BooleanField(verbose_name='es imagen')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=publicaciones.models.ruta_guardar)),
                ('video', models.FileField(blank=True, null=True, upload_to=publicaciones.models.ruta_guardar)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=200, verbose_name='comentario')),
                ('fecha_publicado', models.DateTimeField(auto_now=True, verbose_name='fecha publicado')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicaciones.Publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
