# Generated by Django 3.0.4 on 2020-05-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='is_liked',
            field=models.BooleanField(default=False, verbose_name='is liked'),
        ),
    ]
