# Generated by Django 3.0.4 on 2020-03-30 16:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicaciones', '0003_megusta'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='megusta',
            unique_together={('usuario', 'publicacion')},
        ),
    ]
