# Generated by Django 3.0.4 on 2020-05-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0003_remove_publicacion_is_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_editado',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha editado'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_publicado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha publicado'),
        ),
    ]
